name: Build Kernel

on:
  workflow_dispatch:
  watch:
    types: [started]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
           
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: setup package
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y dialog bash sed wget git curl zip tar jq expect make cmake automake autoconf llvm lld lldb clang gcc binutils bison perl gperf gawk flex bc python3 zstd openssl unzip cpio bc bison build-essential ccache liblz4-tool libsdl1.2-dev libstdc++6 libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zlib1g-dev libncurses5-dev bzip2 git gcc g++ libssl-dev gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi dos2unix kmod python2 aria2 glibc-source

      - name: Clone environments
        run: |
          git clone --depth=1 https://gitlab.com/LeCmnGend/clang.git -b clang-14 toolchain
          git clone --depth=1 https://github.com/bintang774/anykernel.git anykernel

      - name: Cleanup
        run: |
          make clean
          make mrproper
          rm -rf out
          find . -type f -exec chmod 777 {} +
          
      - name: Build Kernel
        run: |
          sleep 10
          $(pwd)/build.sh
